```yaml

name: what_the_fish
description: "What the Fish - AI-powered fish identification app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  
  # Camera & Image
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  image: ^4.1.7
  path_provider: ^2.1.2
  
  # Animations
  lottie: ^3.1.0
  rive: ^0.12.4
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # HTTP & API
  http: ^1.2.0
  dio: ^5.4.1
  
  # Utilities
  uuid: ^4.3.3
  intl: ^0.19.0
  share_plus: ^7.2.2
  permission_handler: ^11.3.0
  
  # Google AI (Gemini)
  google_generative_ai: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/


```
