```yaml

name: what_the_fish

description: "What the Fish - AI-powered fish identification app"

publish_to: 'none'

version: 1.0.0+1

environment:

sdk: ^3.8.1

dependencies:

flutter:

sdk: flutter


# UI & Navigation

cupertino_icons: ^1.0.8


# Camera & Image

camera: ^0.11.0+2

image_picker: ^1.1.2

image: ^4.2.0

path_provider: ^2.1.4


# Animations

lottie: ^3.2.0

rive: ^0.13.20


# State Management

provider: ^6.1.2


# Local Storage

hive: ^2.2.3

hive_flutter: ^1.1.0


# HTTP & API

http: ^1.2.2

dio: ^5.7.0


# Utilities

uuid: ^4.5.1

intl: ^0.19.0

share_plus: ^10.1.2

permission_handler: ^11.3.1


# Google AI (Gemini)

google_generative_ai: ^0.4.6

dev_dependencies:

flutter_test:

sdk: flutter

flutter_lints: ^5.0.0

hive_generator: ^2.0.1

build_runner: ^2.4.13

flutter:

uses-material-design: true


assets:

- assets/animations/

- assets/images/

- assets/icons/

```
