name: Build What the Fish App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    name: Test Flutter App
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true
          
      - name: Flutter doctor
        run: flutter doctor -v
        
      - name: Install dependencies
        run: flutter pub get
        
      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs
        
      - name: Analyze code
        run: flutter analyze --fatal-infos
        
      - name: Run tests
        run: flutter test --coverage --reporter=github
        continue-on-error: false

  # ... rest of the workflow remains the same
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs
        
      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons
        
      - name: Build App Bundle
        run: flutter build appbundle --release --no-tree-shake-icons
        
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30
          
      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: build/app/outputs/bundle/release/app-release.aab
          retention-days: 30

  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true
          
      - name: Enable web
        run: flutter config --enable-web
        
      - name: Install dependencies
        run: flutter pub get
        
      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs
        
      - name: Build web
        run: flutter build web --release --web-renderer html
        
      - name: Upload web build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web/
          retention-days: 30
          
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-android, build-web]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download Android APK
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: ./release-files/
          
      - name: Download Android AAB
        uses: actions/download-artifact@v4
        with:
          name: android-aab
          path: ./release-files/
          
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: What the Fish v${{ github.run_number }} (${{ steps.date.outputs.date }})
          body: |
            🐟 **What the Fish** - AI-powered fish identification app
            
            ## 📱 Downloads
            - **Android APK**: Direct installation file
            - **Android AAB**: Google Play Store upload file
            - **Web Version**: Available at GitHub Pages
            
            ## ✨ Features
            - AI-powered fish identification using Google Gemini
            - Fish edibility analysis with safety warnings
            - Camera and gallery integration
            - Offline history storage with Hive database
            - Ocean-themed UI with Lottie animations
            - Cross-platform compatibility (Android/iOS/Web)
            
            ## 🚀 Installation
            **Android**: Download the APK file and install directly
            **Web**: Visit the GitHub Pages deployment
            
            Built with Flutter & Google Gemini AI 🚀
          draft: false
          prerelease: false
          
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release-files/app-release.apk
          asset_name: what-the-fish-v${{ github.run_number }}.apk
          asset_content_type: application/vnd.android.package-archive
          
      - name: Upload AAB to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release-files/app-release.aab
          asset_name: what-the-fish-v${{ github.run_number }}.aab
          asset_content_type: application/octet-stream
