name: Build What the Fish App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Flutter app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Generate code
        run: flutter packages pub run build_runner build --delete-conflicting-outputs
        
      - name: Run tests
        run: flutter test
        
      - name: Analyze code
        run: flutter analyze

  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'
          
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Generate code
        run: flutter packages pub run build_runner build --delete-conflicting-outputs
        
      - name: Build APK
        run: flutter build apk --release
        
      - name: Build App Bundle
        run: flutter build appbundle --release
        
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
      - name: Upload App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: android-aab
          path: build/app/outputs/bundle/release/app-release.aab

  build-ios:
    name: Build iOS App
    runs-on: macos-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Generate code
        run: flutter packages pub run build_runner build --delete-conflicting-outputs
        
      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign
        
      - name: Create IPA
        run: |
          mkdir -p build/ios/ipa
          cp -r build/ios/Release-iphoneos/Runner.app build/ios/ipa/
          
      - name: Upload iOS Build
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: build/ios/ipa/

  build-web:
    name: Build Web App
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'
          
      - name: Enable Flutter Web
        run: flutter config --enable-web
        
      - name: Get dependencies
        run: flutter pub get
        
      - name: Generate code
        run: flutter packages pub run build_runner build --delete-conflicting-outputs
        
      - name: Build Web
        run: flutter build web --release
        
      - name: Upload Web Build
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web/
          
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-android, build-ios, build-web]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Android APK
        uses: actions/download-artifact@v3
        with:
          name: android-apk
          path: ./artifacts/
          
      - name: Download Android AAB
        uses: actions/download-artifact@v3
        with:
          name: android-aab
          path: ./artifacts/
          
      - name: Download iOS Build
        uses: actions/download-artifact@v3
        with:
          name: ios-app
          path: ./artifacts/
          
      - name: Download Web Build
        uses: actions/download-artifact@v3
        with:
          name: web-build
          path: ./artifacts/web/
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: What the Fish v${{ github.run_number }}
          body: |
            🐟 **What the Fish** - AI-powered fish identification app
            
            ## 📱 Downloads
            - **Android**: app-release.apk (install directly)
            - **Android Play Store**: app-release.aab (upload to Play Store)
            - **iOS**: Runner.app (requires Xcode for signing)
            - **Web**: Available at GitHub Pages
            
            ## ✨ Features
            - AI-powered fish identification using Google Gemini
            - Camera and gallery integration
            - Offline history storage
            - Ocean-themed UI with animations
            - Cross-platform compatibility
            
            ## 🚀 Installation
            - **Android**: Download and install the APK file
            - **iOS**: Build in Xcode with proper code signing
            - **Web**: Visit the GitHub Pages deployment
            
            Built with Flutter 3.32.8 🚀
          files: |
            ./artifacts/app-release.apk
            ./artifacts/app-release.aab
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
